name: inven_fact
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2 # Para cachear imágenes
  image_picker: ^1.2.0
  cached_network_image: ^3.4.1
  http: ^1.4.0
  path: ^1.9.0
  sunmi_printer_plus: ^4.1.1
  qr_flutter: ^4.1.0
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.0
  sqlite3_flutter_libs: ^0.5.0
  mobile_scanner: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true